# Generated by Django 3.0.8 on 2020-07-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('link', models.URLField()),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('linkedin', models.URLField()),
                ('resume', models.FileField(upload_to='resume/%Y/%m/%d/')),
                ('skype', models.CharField(max_length=100)),
                ('twitter', models.URLField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('git', models.URLField()),
                ('hackerrank', models.URLField()),
                ('datacamp', models.URLField()),
                ('medium', models.URLField()),
                ('hackerearth', models.URLField()),
                ('codechef', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('intro', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=200)),
                ('long_description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='project/thumbnails/')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkAcademics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('undergraduation', models.TextField(max_length=500)),
                ('postgraduation', models.TextField(blank=True, max_length=500)),
                ('workexperience1', models.TextField(max_length=500)),
                ('workexperience2', models.TextField(blank=True, max_length=500)),
                ('workexperience3', models.TextField(blank=True, max_length=500)),
                ('workexperience4', models.TextField(blank=True, max_length=500)),
                ('workexperience5', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
