# Generated by Django 3.0.8 on 2020-07-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicsWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('undergraduation', models.TextField(max_length=500)),
                ('postgraduation', models.TextField(blank=True, max_length=500)),
                ('workexperience1', models.TextField(max_length=500)),
                ('workexperience2', models.TextField(blank=True, max_length=500)),
                ('workexperience3', models.TextField(blank=True, max_length=500)),
                ('workexperience4', models.TextField(blank=True, max_length=500)),
                ('workexperience5', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('intro', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=200)),
                ('long_desctiption', models.TextField(max_length=500)),
            ],
        ),
    ]
