# Generated by Django 3.0.8 on 2020-07-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcademicsWork',
            new_name='WorkAcademics',
        ),
    ]
