# Generated by Django 3.0.8 on 2020-07-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200709_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('link', models.URLField()),
            ],
        ),
    ]
