# Generated by Django 3.0.8 on 2020-07-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_accomplishments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accomplishments',
            new_name='Accomplishment',
        ),
    ]
