# Generated by Django 3.0.8 on 2020-07-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200709_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishment',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
