# Generated by Django 3.0.8 on 2020-07-11 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='project/thumbnails/%Y%m%d'),
            preserve_default=False,
        ),
    ]
