# Generated by Django 3.0.8 on 2020-07-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_project_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('linkedin', models.URLField()),
                ('resume', models.FileField(upload_to='resume/')),
                ('skype', models.CharField(max_length=100)),
                ('twitter', models.URLField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('git', models.URLField()),
                ('hackerrank', models.URLField()),
                ('datacamp', models.URLField()),
                ('medium', models.URLField()),
                ('hackerearth', models.URLField()),
                ('codechef', models.URLField()),
            ],
        ),
    ]
