# Generated by Django 3.0.8 on 2020-07-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contact_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='long_desctiption',
            new_name='long_description',
        ),
        migrations.AlterField(
            model_name='contact',
            name='resume',
            field=models.FileField(upload_to='resume/%Y/%m/%d/'),
        ),
    ]
